language: ruby
rvm:
  - 1.9.3
  - 2.0.0
before_script:
  - cp test/config.yml.default test/config.yml
only:
  - master
notifications:
  email: false
  webhooks:
    urls:
      - http://buildlight.collectiveidea.com/
    on_start: true
