language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - rbx
  - jruby
env:
  - DB=postgresql
  - DB=mysql
only:
  - master
notifications:
  email: false
  webhooks:
    urls:
      - http://buildlight.collectiveidea.com/
    on_start: true